- hosts: localhost
  connection: local

  vars:
    container_ports:
      flask: 5000
      node: 3000

    host_ports:
      flask: 8081
      node: 8082

  tasks:
    - name: Stop existing container
      docker_container:
        name: "{{ service }}"
        state: absent

    - name: Run container
      docker_container:
        name: "{{ service }}"
        image: "oriyahazan/{{ service }}:{{ tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_ports[service] }}:{{ container_ports[service] }}"
